import java.nio.file.Paths;
import java.security.PrivateKey;
import java.util.Properties;
import java.util.Set;

import api.RestListener;
import connection.Bloc;
import connection.CryptoBridge;

public class Start {

  // ALWAYS UPDATE pem using autogenerated connection-org1.json in energy-network !!!!!


  public static void main(String[] args) throws Exception {
    RestListener rest = new RestListener();
    rest.start();


  }
}