import java.nio.file.Paths;
import java.security.PrivateKey;
import java.util.Properties;
import java.util.Set;

import connection.Bloc;
import connection.CryptoBridge;

public class Test {

  // ALWAYS UPDATE pem using autogenerated connection-org1.json in energy-network !!!!!


  public static void main(String[] args) throws Exception {
    Bloc bloc = new Bloc();
    bloc.connect();
    bloc.queryAllWallets();


  }
}