# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Project title: Red Prueba
# File name: crypto-config.yaml
# File creation date: February 27, 2021
# Last modification date: February 27, 2021
# Modification done by: AFMH
# 

version: '2'

volumes:
  orderer.ecotoken.io:
  peer0.government1.gov:
  peer0.ngo1.org:
  peer0.startup1.com:

networks:
  byfn:

services:

  orderer.ecotoken.io:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.ecotoken.io
    container_name: orderer.ecotoken.io
    networks:
      - byfn

  peer0.government1.gov:
    container_name: peer0.government1.gov
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.government1.gov
    networks:
      - byfn

  peer0.ngo1.org:
    container_name: peer0.ngo1.org
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ngo1.org
    networks:
      - byfn

  peer0.startup1.com:
    container_name: peer0.startup1.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.startup1.com
    networks:
      - byfn
      
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      #- FABRIC_LOGGING_SPEC=INFO
      - FABRIC_LOGGING_SPEC=ERROR
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.government1.gov:5051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/government1.gov/peers/peer0.government1.gov/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/government1.gov/peers/peer0.government1.gov/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/government1.gov/peers/peer0.government1.gov/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/government1.gov/users/Admin@government1.gov/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/hyperledger/fabric-samples/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.ecotoken.io
      - peer0.government1.gov
      - peer0.ngo1.org
      - peer0.startup1.com
    networks:
      - byfn
