# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.ecotoken.io:
    container_name: orderer.ecotoken.io
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/ecotoken.io/orderers/orderer.ecotoken.io/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/ecotoken.io/orderers/orderer.ecotoken.io/tls/:/var/hyperledger/orderer/tls
        - orderer.ecotoken.io:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
############################# ORG1 #############################
  peer0.government1.gov:
    container_name: peer0.government1.gov
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.government1.gov
      - CORE_PEER_ADDRESS=peer0.government1.gov:5051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:5051
      - CORE_PEER_CHAINCODEADDRESS=peer0.government1.gov:5052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:5052
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer1.government1.gov:5056
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.government1.gov:5051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/government1.gov/peers/peer0.government1.gov/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/government1.gov/peers/peer0.government1.gov/tls:/etc/hyperledger/fabric/tls
        - peer0.government1.gov:/var/hyperledger/production
    ports:
      - 5051:5051

############################# ORG2 #############################
  peer0.ngo1.org:
    container_name: peer0.ngo1.org
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.ngo1.org
      - CORE_PEER_ADDRESS=peer0.ngo1.org:6051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6051
      - CORE_PEER_CHAINCODEADDRESS=peer0.ngo1.org:6052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.ngo1.org:6051
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer1.ngo1.org:6056
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/ngo1.org/peers/peer0.ngo1.org/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/ngo1.org/peers/peer0.ngo1.org/tls:/etc/hyperledger/fabric/tls
        - peer0.ngo1.org:/var/hyperledger/production
    ports:
      - 6051:6051

############################# ORG3 #############################
  peer0.startup1.com:
    container_name: peer0.startup1.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.startup1.com
      - CORE_PEER_ADDRESS=peer0.startup1.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.startup1.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.startup1.com:7051
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer1.startup1.com:7056
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/startup1.com/peers/peer0.startup1.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/startup1.com/peers/peer0.startup1.com/tls:/etc/hyperledger/fabric/tls
        - peer0.startup1.com:/var/hyperledger/production
    ports:
      - 7051:7051


