# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.ciencia.edu:
    container_name: orderer.ciencia.edu
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/ciencia.edu/orderers/orderer.ciencia.edu/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/ciencia.edu/orderers/orderer.ciencia.edu/tls/:/var/hyperledger/orderer/tls
        - orderer.ciencia.edu:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
############################# ORG1 #############################
  peer0.department1.university1.edu:
    container_name: peer0.department1.university1.edu
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.department1.university1.edu
      - CORE_PEER_ADDRESS=peer0.department1.university1.edu:5051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:5051
      - CORE_PEER_CHAINCODEADDRESS=peer0.department1.university1.edu:5052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:5052
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer1.department1.university1.edu:5056
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.department1.university1.edu:5051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/department1.university1.edu/peers/peer0.department1.university1.edu/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/department1.university1.edu/peers/peer0.department1.university1.edu/tls:/etc/hyperledger/fabric/tls
        - peer0.department1.university1.edu:/var/hyperledger/production
    ports:
      - 5051:5051

############################# ORG2 #############################
  peer0.department2.university2.edu:
    container_name: peer0.department2.university2.edu
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.department2.university2.edu
      - CORE_PEER_ADDRESS=peer0.department2.university2.edu:6051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:6051
      - CORE_PEER_CHAINCODEADDRESS=peer0.department2.university2.edu:6052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:6052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.department2.university2.edu:6051
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer1.department2.university2.edu:6056
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/department2.university2.edu/peers/peer0.department2.university2.edu/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/department2.university2.edu/peers/peer0.department2.university2.edu/tls:/etc/hyperledger/fabric/tls
        - peer0.department2.university2.edu:/var/hyperledger/production
    ports:
      - 6051:6051

############################# ORG3 #############################
  peer0.department3.university3.edu:
    container_name: peer0.department3.university3.edu
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.department3.university3.edu
      - CORE_PEER_ADDRESS=peer0.department3.university3.edu:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.department3.university3.edu:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.department3.university3.edu:7051
      #- CORE_PEER_GOSSIP_BOOTSTRAP=peer1.department3.university3.edu:7056
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/department3.university3.edu/peers/peer0.department3.university3.edu/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/department3.university3.edu/peers/peer0.department3.university3.edu/tls:/etc/hyperledger/fabric/tls
        - peer0.department3.university3.edu:/var/hyperledger/production
    ports:
      - 7051:7051


